### ISSUE TITLE
get BlazorApp telemetry to show up in Jaeger

### ISSUE THREAD

**Issue by adamfoneil** [adamfoneil/OpenTelemetryDemo#1]
This is just a Hello, World kind of task -- I'm trying to get something super basic working.

I'm adding OpenTelemetry [here](https://github.com/adamfoneil/OpenTelemetryDemo/blob/master/OpenTelemetryDemo/Program.cs#L11) at startup.

The goal is to be able to run the app Blazor Server app, click a few links (Home, Counter, Telemetry), and see traces in the Jaeger dashboard. There should be a "BlazorApp" option in the Service drdopdown. Note there is a link to the Jaeger dashboard [here](https://github.com/adamfoneil/OpenTelemetryDemo/blob/master/OpenTelemetryDemo/Components/Layout/NavMenu.razor#L30).

![image](https://github.com/user-attachments/assets/15ad0631-9e05-4515-8174-74742ad0046c)

Eventually the goal is to see EF Core database traffic as well, but for this issue, I just want to see "Blazor App" in the Jaeger Service dropdown and see some http traces.

I believe the problem has to do with the [exporter endpoint](https://github.com/adamfoneil/OpenTelemetryDemo/blob/master/OpenTelemetryDemo/Program.cs#L22) not being right, but I don't know what to put here. Note the [docker compose](https://github.com/adamfoneil/OpenTelemetryDemo/blob/master/docker-compose.yml) where this is setup. I'm a Docker noob, so this is likely the reason I'm struggling.

**Comment by wasabii** [comment]
You'd need to deploy a copy of Jaeger or some other APM in your hosting environment, not just locally.

**Comment by wasabii** [comment]
You're doing it more complicated than need be. If you just want to run a local copy of Jaeger, you have two different easy paths: a) download jaeger from the internet and run it. They have a Windows distribution like any other peice of software. b) use docker to run it as described on their own page: https://www.jaegertracing.io/docs/1.60/getting-started/

Docker Compose is an unnecessary component.

**Comment by wasabii** [comment]
Deploying it in production of course is a different story. For THAT you'll have to get into digital ocean special stuff.

I'd be happy to do a call. I'm here all day.
